Fix release tag issue

diff --git a/deploy/ci/tasks/dev-releases/generate-tag-files.yml b/deploy/ci/tasks/dev-releases/generate-tag-files.yml
--- a/deploy/ci/tasks/dev-releases/generate-tag-files.yml
+++ b/deploy/ci/tasks/dev-releases/generate-tag-files.yml
@@ -20,13 +20,25 @@ run:
 
       cd stratos
 
+      # RELEASE_TAG is the full tag that started the pipleine, e.g. '2.0.0-rc.1' 
       RELEASE_TAG=$(cat .git/ref)
 
-      # RELEASE_TAG is the full tag that started the pipleinee, e.g. '2.0.0-rc.1' 
       VERSION=$(cat package.json | grep version | grep -Po "([0-9\.]?)*")
       COMMIT_HASH=$(git log -1 --format="%h")
       LATEST_TAG=$VERSION-${COMMIT_HASH}
       SOURCE_CODE_REPO=$(git config --get remote.origin.url)
+
+      # Check that the RELEASE_TAG matches the version
+      if [[ "${RELEASE_TAG}" != ${VERSION}* ]]; then
+        echo ".git/ref is not the expected release tag - falling back to git describe"
+        RELEASE_TAG=$(git describe)
+        if [[ "${RELEASE_TAG}" != ${VERSION}* ]]; then
+          echo "Error: Can not get tag for this release - got ${RELEASE_TAG}"
+          exit 1
+        fi
+      fi
+
+      echo "Got Release tag ${RELEASE_TAG}"
 
       echo "Got version $VERSION from package.json."
 
